# Generated by Django 2.0.1 on 2018-06-05 13:56

from django.conf import settings
import django.contrib.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('text', models.CharField(max_length=3750)),
                ('date', models.DateTimeField(verbose_name='published')),
                ('user', models.ForeignKey(on_delete=models.SET(django.contrib.auth.get_user_model), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
